version: '3'
services:
  nodejs:
    container_name: restful-nodejs
    command: ["npm", "start"]
    image: node:8.10.0
    working_dir: /usr/src/app
    restart: always
    tty: false
    ports:
      - "8001:8001"
    volumes:
      - ./project:/usr/src/app
    networks:
      - restful-net
    depends_on:
      - mongo
  mongo:
    container_name: restful-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - restful-data:/data/db
    networks:
      - restful-net
  mongo-express:
    container_name: restful-mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    restart: always
    tty: true
    environment:
      - "ME_CONFIG_MONGODB_SERVER=mongo"
      - "ME_CONFIG_BASICAUTH_USERNAME="
      - "ME_CONFIG_BASICAUTH_PASSWORD="
    networks:
      - restful-net
    depends_on:
      - mongo
  swagger-ui:
    container_name: restful-swagger-ui
    image: swaggerapi/swagger-ui
    restart: always
    tty: true
    ports:
      - "80:8080"
    environment:
      - "API_URL=http://localhost:8001/swagger"
    networks:
      - restful-net
    depends_on:
      - nodejs
networks:
  restful-net:
volumes:
  restful-data:
